version: "3.7"
services:
  app:
    build:
      args:
        user: salimpio
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: salimpio
    container_name: salimpio-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - salimpio

  db:
    image: mariadb
    container_name: salimpio-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - salimpio-mariadb:/var/lib/mysql
    networks:
      - salimpio

  nginx:
    image: nginx:alpine
    container_name: salimpio-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - salimpio

networks:
  salimpio:
    driver: bridge
volumes:
  salimpio-mariadb: